### ISSUE TITLE
ponder hit しない （no ponder hit）

### ISSUE THREAD

**Issue by hmatsuya** [hmatsuya/chotgun#1]
@test597 さんによると:
> 度々失礼いたします。
> goの部分をgo depth 16にしても改善しませんでした。
> デバッグログを見たのですが、明らかにponderがヒットしているにも関わらずno ponder hitとなっていました。
> ログを添付いたします。
> log.txt

**Comment by hmatsuya** [comment]
@test597
問題調査のため、以下の2ファイルをこちらに添付してくださいますか。
- 編集済みの chotgun.py
- 起動用バッチファイル

また、将棋所のエンジン設定画面のスクリーンショット等もあると助かります。

**Comment by test597** [comment]
分かりました。
少しお待ちください

**Comment by test597** [comment]
ご希望があった3つのファイルです。
[chotgun.zip](https://github.com/hmatsuya/chotgun/files/5039857/chotgun.zip)

**Comment by hmatsuya** [comment]
@test597 度々すみません。 hosts.txt もいただけますでしょうか。

**Comment by hmatsuya** [comment]
先にいただいたログファイルを添付
[log.txt](https://github.com/hmatsuya/chotgun/files/5039923/log.txt)

**Comment by test597** [comment]
こちらになります
[hosts.txt](https://github.com/hmatsuya/chotgun/files/5039931/hosts.txt)

**Comment by hmatsuya** [comment]
いただいたファイルには該当箇所が無いのに、multiPVが32に設定されているようです。
もしかしたら `engine_options.txt` を使用していますか？
もしあればそちらもいただけますでしょうか。

**Comment by test597** [comment]
engine_option.txtは使用しておりません。
multipvではなくスレッドの方を32に設定した記憶ならあるのですが、、、

**Comment by hmatsuya** [comment]
ログを見ると、chotgunはmultiPVに1を設定しているのに、
なぜかUSIエンジンはmultiPV 32で思考しているように見えます。
もしかしたらUSIエンジン自体が改造されていて、threadsをmultiPVに設定しているのかもしれません。
念のため、普通のやねうら王を使ってみてください。

（chotgun.pyはマルチポンダーの候補手を探すときは multiPVに n_jobs (hosts.txtの行数)を、
それ以外の思考時にはmultiPVに1を設定する仕様です。）

また、テストをする際は対戦相手の定跡をオフにするか、定跡が切れる局面まで手をを進めてください。
相手に即指されると、こちらがponderする時間がありませんので…

上記の2点に留意して、再度テストしてみてくださいますか。

**Comment by test597** [comment]
通常やねうら王を使い、定跡なしで対局させてみましたがやはりダメでした。
pythonやライブラリのバージョンとかの問題でしょうかね？（pythonは3.7.5を使用しています）

**Comment by hmatsuya** [comment]
自分の使用しているPythonのバージョンはWSL(Ubuntu)版の3.6.9ですが、
そこは問題ないと思います。いただいたログを見たところ、エラーや警告は出ていないので。

いただいたログの301行目に`>1:setoption name USI_Ponder value false`とあり、
将棋所から先読みponderをしないように言われています。
これがあると、一番当たる可能性の高い第1候補手でponder hitしなくなってしまいます。

いただいたエンジン設定のスクリーンショットでは、USI_Ponderがtrueに設定されておりますが、
なぜ矛盾が生じるか、原因を調べてみてくださいますか。

**Comment by hmatsuya** [comment]
参考までに自分のテスト環境のバッチファイルやログ等を添付します。

[chotgun_test.zip](https://github.com/hmatsuya/chotgun/files/5044835/chotgun_test.zip)

ログでは後手（エンジン2）でのみ chotgun.py を使用しています。

**Comment by test597** [comment]
それは将棋所でエンジン設定をスクショしようとした時、USI_Ponderがfalseになっているのが原因かと思いTrueにして試してみましたがダメでした。
恐らくその時に設定されたのをそのまま引き継いでいるのかと

**Comment by hmatsuya** [comment]
こちらでは問題が再現しないため、問題は設定や環境によるものだと思われます。
正しい情報をいただけなければ、こちらの調査が無駄になってしまいます。

新しいログと、**それと同時に使用した**バッチファイル、pythonスクリプト、設定画面をいただけたならば
こちらもう少し調査したいと思います。

こちらでの調査が不要な場合は、この issue をクローズしたいと思います。

**Comment by test597** [comment]
将棋所の設定を見直していたら解決しました！
ご迷惑おかけして申し訳ございません、ご対応ありがとうございました。

**Comment by hmatsuya** [comment]
問題が解決して良かったです！

マルチポンダーを使って勝つには、なかなか使い方が難しいのですが
設定や改良を頑張ってみてください。

例えば白ビールでは、相手側のponderを外すような工夫もしているそうです。
そしてうまくいったら、設定等を教えて下さい😉
